### ISSUE TITLE
Problem of use GeofencingApi

### ISSUE THREAD

**Issue by Larnoo** [mapzen/lost#122]
## After I addGeofences, how can I receive a callback when I leave the geofencing?

```
LocationServices.GeofencingApi.addGeofences(client, request, pendingIntent);
```

How can I receive a callback when I leave the geofencing?

**Comment by ecgreb** [comment]
With version 2.0.1-SNAPSHOT you can explicitly set the transition type when constructing a `Geofence` to `GEOFENCE_TRANSITION_EXIT` although this should be enabled by default in the 2.0 release.

**Comment by sarahlensing** [comment]
Implemented https://github.com/mapzen/lost/blob/25d4fda39a44c28d314f313d701f49f3dfc2e3c7/lost/src/main/java/com/mapzen/android/lost/internal/GeofenceIntentHelper.java#L24
