### ISSUE TITLE
FusedLocationApi won't send initial location

### ISSUE THREAD

**Issue by westnordost** [mapzen/lost#141]
### Description
Okay, I am not completely sure if this is a bug or if I am using it wrong. I make a location request with a high smallest displacement while no last location is known (to LOST's FusedLocationApi). Then, I get no call to `onLocationChanged` as long as I do not move at least the given displacement first (and/or wait the interval, I did not test that).
However, I would expect that I get first **one** call to `onLocationChanged` regardless of the `smallestDisplacement` and `interval` since _no previous location was known_.

### Steps to Reproduce
1. I.e. using the code below
2. Have never before used the application, so that `getLastLocation` will return null
3. Make a location request (see below) with a high smallest displacement and/or a high interval
4. Witness that `onLocationChanged` not called. After I move for 1000m, then finally I get a call to `onLocationChanged`. (Tested only in the emulator)
```
LocationRequest request = LocationRequest.create()
		.setPriority(LocationRequest.PRIORITY_HIGH_ACCURACY)
		.setSmallestDisplacement(1000)
		.setInterval(5*60*1000); // 5 minutes

Location location = LocationServices.FusedLocationApi.getLastLocation(lostApiClient);
if(location != null)
{
	this.onLocationChanged(location);
}

LocationServices.FusedLocationApi.requestLocationUpdates(lostApiClient, request, this);
```

### Lost & Android Version
2.1.1 on Android 6.0

**Comment by sarahlensing** [comment]
At the moment, location callbacks are in fact triggered if no previous location is known: https://github.com/mapzen/lost/blob/master/lost/src/main/java/com/mapzen/android/lost/internal/FusionEngine.java#L183

I did some testing with GooglePlayServices and observed that it returns the last known location as the initial location passed to `onLocationChanged` (bearing, lat, and long are all the same). Perhaps we could update LOST to do this as well (with some checks for "freshness" to ensure we aren't passing a very old location). 

cc/ @ecgreb

**Comment by westnordost** [comment]
Are initial location callbacks also triggered if LocationRequest restrictions like `.setSmallestDisplacement(1000)` are set an no previous location is known? Because this would be contrary to my findings.

Note it is not about 
```
Location location = LocationServices.FusedLocationApi.getLastLocation(lostApiClient);
if(location != null)
{
	this.onLocationChanged(location);
}
```
, actually, it is quite irrelevant to the bug description. The issue is that there is _no_ last location and I then as soon as I get a GPS fix, I do not get the callback because I did not move the 1000 meters required.
I could also have made an error during the reproduction and my whole claim is not true, I just want to make sure we understand each other.

**Comment by sarahlensing** [comment]
We currently aren't using the `smallestDisplacement` (or `smallestInterval`) when determining whether to trigger `onLocationChanged` (this will be changing as per https://github.com/mapzen/lost/issues/142 though). At the moment, it is really only `accuracy` which is used to determine whether or not the callback should be triggered.

I will do more testing to repro exactly what happens when there is no last known system location.

**Comment by ecgreb** [comment]
@sarahlensing I do think it would make sense to return the last known location as the first update if it is reasonably fresh (i.e. within `RECENT_UPDATE_THRESHOLD_IN_MILLIS`) but I think we are all in agreement now that is not the same issue reported here. We should create a separate issue for this.

I cannot find anywhere we are currently using `smallestDisplacement` (although I believe we were at some point in the past and _probably_ _should_ _be_) however we are using the `interval` value [when we request location updates](https://github.com/mapzen/lost/blob/master/lost/src/main/java/com/mapzen/android/lost/internal/FusionEngine.java#L125) from the `LocationManager`.

@westnordost have you tried testing the same scenario using Google Play services to see how it behaves under these circumstances? Or by directly invoking the `LocationManager`?

**Comment by westnordost** [comment]
No, I haven't tested that. Will do tomorrow.

**Comment by westnordost** [comment]
I tested it. I can reproduce it:
If I request the permission via LocationManager, I get an initial location immediately.
The same with FusedLocationApi, I do not get an initial location. Actually, I don't get a location at all, even after setting a different location in the emulator.
[MainActivityWithLostApiClient.txt](https://github.com/mapzen/lost/files/628957/MainActivityWithLostApiClient.txt)
[MainActivityWithLocationManager.txt](https://github.com/mapzen/lost/files/628958/MainActivityWithLocationManager.txt)
