### ISSUE TITLE
onLocationChanged is called from a LocationRequest of another fragment

### ISSUE THREAD

**Issue by westnordost** [mapzen/lost#142]
### Description
Not sure if this is expected behavior (=mirroring google play api) or a bug. In any case, it would be good if this was documented:
Requesting different location updates from different places will make the `onLocationChanged` method be called in both places whenever the condition of either location request of any of the two places is fulfilled.

### Steps to Reproduce
I have an activity which requests location updates only every few minutes and only if the user moved quite a bit.
```
LocationRequest request = LocationRequest.create()
		.setPriority(LocationRequest.PRIORITY_HIGH_ACCURACY)
		.setSmallestDisplacement(500)
		.setInterval(3*60*1000); // 3 minutes

LocationServices.FusedLocationApi.requestLocationUpdates(lostApiClient, request, this);
```

Then, I also got a fragment, which creates an own lostApiClient for itself (which I guess points to the same object internally) and requests very frequent location updates, let's say every second.

As soon as that fragment starts requesting location updates, the former mentioned activity starts to get calls every second to `onLocationChanged`.
The activity is doing an expensive operation on `onLocationChanged`, I expected that the parameters of my location request would be respected.

### Lost & Android Version
2.1.1 on Android 5.0

**Comment by sarahlensing** [comment]
Thank you for the detailed report! The behavior you are observing is a bug and should be updated to do as you suggest and respect the parameters of the location request. This will also bring it up to par with Play Services. Stay tuned for a fix coming soon...
