### ISSUE TITLE
startResolutionForResult don't show dialog like google play service location

### ISSUE THREAD

**Issue by SylvainHocq** [mapzen/lost#189]
Hello, 
I tried to witch my code from google play to lost.
And i'm surprised to see that the behavior of the method startResolutionForResult is not similar.
Google show a dialog when this method is called.
Lost launched the system activity to enable GPS

Did i forget to do something?

Personally i'm prefered the dialog because the user stay in my application and he just need to valid the dialog.

i use lost 2.1.2 and i am on android 7.0 or 6.0.1

**Comment by ecgreb** [comment]
Unfortunately modifying settings from your app requires system level
permissions which Lost does not have so redirecting to the settings app is
the best workaround we can provide for now.

**Comment by sarahlensing** [comment]
That's correct, unfortunately we cannot provide a dialog given the permission requirements. I'm going to close this issue as there isn't anything we can do to change this at the moment. Thank you for your report!
