### ISSUE TITLE
two client, one with mock, the other without

### ISSUE THREAD

**Issue by SylvainHocq** [mapzen/lost#195]
Hello, 
It is impossible actually to use two client one with mock enabled and the other without mock.

When i use  `LocationServices.FusedLocationApi.setMockMode(fragmentClient, true);` in fact, this activate mock for all clients.

Because when i do that in the fragment of the sample MultipleLocationListenerMultipleClientsActivity, no locations are received in fragment, neither in activity

I use lost 2.2.0

Thanks.

**Comment by sarahlensing** [comment]
Hi and thanks for opening the issue! It is not possible to have mock mode enabled for one client and disabled for another. Toggling mock mode will [affect all clients](http://mapzen.github.io/lost/com/mapzen/android/lost/api/FusedLocationProviderApi.html#setMockMode-com.mapzen.android.lost.api.LostApiClient-boolean-).

I'm going to close this issue but please feel free to open a new one if something else comes up!
