### ISSUE TITLE
Location updates via PendingIntent

### ISSUE THREAD

**Issue by ecgreb** [mapzen/LOST#22]

**Comment by bleege** [comment]
@ecgreb @mjcunningham I started looking into implementing this today.  For the most part it seems like it should be pretty straightforward up until the point of passing the updated `Location` object to the `PendingIntent`.  What I'm thinking is that `FusedLocationProviderApiImpl` would be updated to:

1. Have an instance variable to store the reference to the passed in `PendingIntent` similar to what `LocationListener` does.
1. Update `reportLocation()` to send the new `Location` to the source of the `PendingIntent` assuming the instance variable is non null.

The part that I'm struggling with is how to actually pass the new `Location` object to the `PendingIntent` as it seems to be a bit of black box as to what it actually sends data to (Activity, BroadcastReceiver, etc).  It seems like I should just be able to update the `Location` object somewhere and then call `send()` on the `PendingIntent`.  Normally this would be the original `Intent` that was sent in to the original `PendingIntent` creation method but it doesn't seem like it's possible to get this data back from the `PendingIntent`.

Thoughts?

**Comment by ecgreb** [comment]
Let's try to model this after how its handled in the framework. In the `LocationManagerService` it creates a new `Intent` (rather than trying to re-use the one from the `PendingIntent`) and stuffs a copy of the `Location` update into it as an extra.

https://github.com/android/platform_frameworks_base/blob/master/services/core/java/com/android/server/LocationManagerService.java#L835

We don't actually need to know what we are sending the data to (`Activty`, `BroadcastReceiver`, etc.) since that should be encoded into the `PendingIntent` itself and routed correctly when we call `send()`.
