### ISSUE TITLE
My Application is started twice

### ISSUE THREAD

**Issue by paulVulog** [mapzen/lost#225]
I am using com.mapzen.android:lost:3.0.1
When I start my Android app, my custom Application class is called twice ( onCreate() ).
If I look at android studio, I can see two processes : 
com.my.package.debug <- my app
com.my.package.debug:lost <- ?

What does it mean ? Looks like Lost start a new process with my custom application.
My Application class initializes a lot of stuff. I don't want to initialize them twice.
 
Perhaps I am just doing something wrong and it is the expected behavior. What is the best practice to use the library ? I am not sure but I do not remember of this behavior on previous version of LOST.

Thanks !

**Comment by tobrun** [comment]
A solution for this would be similar to what [LeakCanary](https://github.com/square/leakcanary) is doing as they also use a dedicated process:

```java
    if (LeakCanary.isInAnalyzerProcess(this)) {
      // This process is dedicated to LeakCanary for heap analysis.
      // You should not init your app in this process.
      return;
    }
```

**Comment by sarahlensing** [comment]
Thanks @tobrun! This would definitely be the way to go. @paulVulog I've created a PR(https://github.com/mapzen/lost/pull/226) which adds an upgrading from 2.x doc. Feel free to make comments/suggestions on it.

**Comment by paulVulog** [comment]
Amazing. Thanks @sarahlensing for this fast update.
