### ISSUE TITLE
LOST 3.0.2 patch release?

### ISSUE THREAD

**Issue by westnordost** [mapzen/lost#231]
Would it be possible to release a patch release with the fixes for the DeadObjectException and the IllegalStateException soon? 

LOST 3.0.1 causes more than 85% of application crashes for users of my app and since the crashes happen deferred on the main thread, there is nothing I can do about it (as wrapping the LOST calls in try-catch doesn't catch the exception thrown deferred in the main thread).

**Comment by msmollin** [comment]
We are targeting a patch release this week - ideally tomorrow.

**Comment by sarahlensing** [comment]
https://github.com/mapzen/lost/releases/tag/lost-3.0.2
