### ISSUE TITLE
Is orientation provided?

### ISSUE THREAD

**Issue by stepanmazokha** [mapzen/LOST#28]
For instance, with google maps user can change the phone orientation (phone is oriented to the west/east/north etc) and the angle of arrow on a map will be changed. Is this possible with LOST? Or, if not, maybe you could advise me, how to achieve this?

Thanks in advance for help.

**Comment by ecgreb** [comment]
You can call `Location.getBearing()` as whatever value returned by the location provider will be preserved by LOST.

http://developer.android.com/reference/android/location/Location.html#getBearing()
