### ISSUE TITLE
Implement getLocationAvailability and SettingsApi

### ISSUE THREAD

**Issue by ljbade** [mapzen/LOST#35]
Currently LOST provides no way to determine if a devices location services are enabled.

The Google Play API provides [`LocationServices.FusedLocationApi.getLocationAvailability()`](https://developers.google.com/android/reference/com/google/android/gms/location/FusedLocationProviderApi#getLocationAvailability(com.google.android.gms.common.api.GoogleApiClient)) and [`LocationCallback.onLocationAvailability()`](https://developers.google.com/android/reference/com/google/android/gms/location/LocationCallback#onLocationAvailability(com.google.android.gms.location.LocationAvailability))

Further to this LOST is also missing the [`SettingsApi`](https://developers.google.com/android/reference/com/google/android/gms/location/SettingsApi) which provides a dialog to request the user enable the location services.

**Comment by ecgreb** [comment]
Thanks for the feedback. We are planning to support methods these in the next version of LOST.

As a workaround you could query the `LocationManager` directly to determine which providers are enabled using [`LocationManager.getProviders(true)`](https://developer.android.com/reference/android/location/LocationManager.html#getProviders(boolean)) or [`LocationManager.isProviderEnabled(provider)`](https://developer.android.com/reference/android/location/LocationManager.html#isProviderEnabled(java.lang.String)).

**Comment by tobrun** [comment]
@ecgreb Is there an ETA for when the next version of LOST will land?

**Comment by ecgreb** [comment]
There is no set timetable for the next version as of right now but the latest snapshot is always available in the [Sonatype snapshots repo](https://oss.sonatype.org/content/repositories/snapshots/com/mapzen/android/lost/).

**Comment by mjcunningham** [comment]
I don't believe we are currently working on this feature correct @ecgreb? 

@tobrun we'd love a PR if this is something you'd need. Once we merge it it would immediately cut a snapshot that you could grab.

**Comment by ecgreb** [comment]
@mjcunningham correct. Sorry didn't mean to imply this feature was in the latest snapshot (just that we have snapshots automatically deployed now).

It is still as of yet not implemented but contributions are indeed always welcome!

**Comment by ecgreb** [comment]
Created separate issues to track independently

https://github.com/mapzen/LOST/issues/64
https://github.com/mapzen/LOST/issues/65
