### ISSUE TITLE
How to tell if failed to start listening for location updates?

### ISSUE THREAD

**Issue by xbroak** [mapzen/lost#49]
I was expecting some sort of "onConnectFailed", is there not anywhere that reports errors in retrieving location updates and/or problems with "Connect"? E.g. GPS enabled but not working correctly, not providing any coords

**Comment by ecgreb** [comment]
Calling `LostApiClient#connect()`  doesn't actually initialize any location updates so you wouldn't get a GPS error from calling "Connect".

Are you looking for an error response for `FusedLocationProviderApi#requestLocationUpdates(request, listener)`? Currently an error will be logged if the `FusionEngine` is unable to register for GPS or network updates but there is no error response.

I suppose we could implement something similar to [`PendingResult`](https://developers.google.com/android/reference/com/google/android/gms/common/api/PendingResult) and [`Status`](https://developers.google.com/android/reference/com/google/android/gms/common/api/Status) for location update methods that will provide immediate feedback if for some reason we were unable to register for updates with a given provider. But again, this would not really verify the GPS is actively producing valid location updates, just that it exists and we were able to register a listener on it.

**Comment by sarahlensing** [comment]
Closing in favor of https://github.com/mapzen/lost/issues/219
