### ISSUE TITLE
Q: isProviderEnabled & onProviderDisabled/Enabled callbacks

### ISSUE THREAD

**Issue by amayatsky** [mapzen/LOST#55]
Here is a little question, I know this is not the way how the fused location provider works, but is there a way to receive a status of enabled providers and get appropriate callbacks or I should request android.location directly?

**Comment by ecgreb** [comment]
There is no way to do this currently through LOST but I think exposing `onProviderEnabled(String provider)` and `onProviderDisabled(String provider)` in the LOST `LocationListener` would be a nice value add.

https://developer.android.com/reference/android/location/LocationListener.html

Adding enhancement label and tagging for the next release.
