### ISSUE TITLE
Unnecessarily huge method count

### ISSUE THREAD

**Issue by EricKuck** [mapzen/LOST#58]
I have to enable multidex in my very small app just so I can include Mapbox, which includes this. Why is Guava used in something like this? It's completely unsuitable for Android development and should really be avoided at all costs.

**Comment by blair1618** [comment]
It looks as though Guava is not actually used in the library, only in tests. Would #59 help?

**Comment by EricKuck** [comment]
Yep! That's perfect. In the meantime I've excluded it as a dependency of my build, but this should not be necessary. Removing guava saved ~15k methods for me.

**Comment by EricKuck** [comment]
While you're removing dependencies, it appears appcompat is unused as well. Support itself is totally unused except for one annotation, from what I can tell.

**Comment by ecgreb** [comment]
Added an [issue here](https://github.com/mapzen/LOST/issues/61) to revisit appcompat and support library dependencies.
