### ISSUE TITLE
Support multiple location clients

### ISSUE THREAD

**Issue by ecgreb** [mapzen/LOST#62]
We should explore the feasibility of supporting multiple location clients from multiple threads and/or processes.

This primary use case would be for a single application if the UI thread and a service thread both needed to register for location updates via separate clients.

The secondary and potential future use case would be to allow a shared instance of lost to run in a background service that could be used by more than one application.

**Comment by christocracy** [comment]
How could 2 separate applications share the same instance of a class?

The only way another app could receive location-data from another app is indirectly via `#fastestInterval`

**Comment by ecgreb** [comment]
The idea here would be to [export the service](https://developer.android.com/guide/topics/manifest/service-element.html#exported) that contains the `FusionEngine` so a single instance could be shared by multiple clients/applications.
