### ISSUE TITLE
GoogleApiClient and LostApiClient differences

### ISSUE THREAD

**Issue by BharathMG** [mapzen/lost#67]
Hey guys,

Nice work implementing FusedLocation API! Thanks for it. I was going through the code base and it seemed like the FusionEngine just takes care of switching between NETWORK, GPS and PASSIVE location providers based on conditions?

GoogleApiClient implements additional strategies right? Like using Sensor data as a means to accurate the location and also battery saving strategies. Are those things in pipeline? 

Thanks again!

**Comment by ecgreb** [comment]
Possible future work captured in #30. Feel free to reopen if you have additional related questions.
