### ISSUE TITLE
getLastLocation() throws SecurityException on API 23+

### ISSUE THREAD

**Issue by amayatsky** [mapzen/LOST#68]
Unfortunately we need to check if the ACCESS_FINE_LOCATION permission is granted every time we call this function.
Is this an intended behavior or some improvement is possible?

`Process: com.amayatsky.test, PID: 5948
                                                                           java.lang.SecurityException: "passive" location provider requires ACCESS_FINE_LOCATION permission.`

**Comment by ecgreb** [comment]
Nice catch. `FusionEngine#getLastLocation()` should be updated to respect runtime permissions and fallback to network provider only if `ACCESS_FINE_LOCATION` has not been granted.

This also begs the question what should `getLastLocation()` return if no location permissions have been granted? I guess our only option in this case is to return `null`.

**Comment by amayatsky** [comment]
Same exception for requestLocationUpdates by the way. Maybe this should be
tracked as a separate issue.

3 Авг 2016 г. 23:54 пользователь "Chuck Greb" <notifications@github.com>
написал:

**Comment by ecgreb** [comment]
Yeah a lot of this stuff was written before Android M permissions were a thing so there are some questions that need to be answered around this stuff.

However in this case if a client application requests location updates with `PRIORITY_HIGH_ACCURACY` without checking permissions and the `ACCESS_FINE_LOCATION` has not been granted then throwing a `SecurityException` is probably the correct behavior.

**Comment by msmollin** [comment]
I guess a good question would be: what does play services do?

**Comment by ecgreb** [comment]
Ok so I put together a quick sample app based on [this tutorial](https://developer.android.com/training/location/index.html) and verified the following regarding the behavior of Google Play services (version 9.4.0):

1. Calling `LocationServices.FusedLocationApi.getLastLocation(mGoogleApiClient)` when no location permissions have been granted does indeed return `null` and no exception is thrown.

2. Calling `LocationServices.FusedLocationApi.requestLocationUpdates(mGoogleApiClient, LocationRequest.create(), this)` when no location permissions have been granted throws a `SecurityException` with the following message.

```
java.lang.SecurityException: Client must have ACCESS_COARSE_LOCATION or ACCESS_FINE_LOCATION permission to perform any location operations.
```
