### ISSUE TITLE
Fused provider fails to attach LocationResult to intent

### ISSUE THREAD

**Issue by ecgreb** [mapzen/LOST#80]
`FusedLocationProviderApiImpl#reportLocation(Location)` should attach `LocationResult` extra to callback intents.

**Comment by sarahlensing** [comment]
https://github.com/mapzen/LOST/pull/85/files#diff-6a9b2934042ff1ceb34b490e280bb9fbR152

Closed by https://github.com/mapzen/LOST/pull/85
