### ISSUE TITLE
Fix tests using Thread.sleep(100)

### ISSUE THREAD

**Issue by ecgreb** [mapzen/lost#84]
### Description

A number of tests are currently ignored due to intermittent failures. These tests all depend on concurrency used by `MockEngine` to deliver mock location updates from a GPX trace file. We need to find a better way to test the behavior of `FusedLocationProviderApi.setMockTrace(File)` without the use of `Thread.sleep(100)`.

### Steps to Reproduce

Remove all `@Ignore("Intermittently failing. Find a better way to test without Thread.sleep(100)")` annotations and run tests.

### Lost & Android Version

LOST 1.1.1

**Comment by sarahlensing** [comment]
👍
