### ISSUE TITLE
Circle CI is not building fork pull requests

### ISSUE THREAD

**Issue by ecgreb** [mapzen/lost#94]
Why isn't Circle CI building pull requests coming from forks of this project? (for example https://github.com/mapzen/LOST/pull/91)

According to the Circle CI docs fork pull requests should build just without any environment variables configured via the web UI (sonatype username/password) which is fine since these are only needed to deploy snapshots from master.

https://circleci.com/docs/fork-pr-builds/

Email has been sent to @circleci support and we are awaiting a reply.

**Comment by sarahlensing** [comment]
As per their recommendation a post was created here:

https://discuss.circleci.com/t/fork-pull-requests-public-repos/6109

**Comment by ecgreb** [comment]
Project settings updated. Working now.

**Comment by hardysim** [comment]
> Project settings updated. Working now.

@ecgreb is there something one need to change? We have the same problem of a fork-PR not being build.

**Comment by ecgreb** [comment]
@hardysim try under the Circle web UI Settings > Advanced Settings make sure "Free and Open Source" and "Build forked pull requests" are both enabled.
